### ISSUE TITLE
Harvest hangs on UTF-8 errors

### ISSUE THREAD

**Issue by mjlassila** [miku/metha#1] opened 2016-11-18 13:26 UTC
I'm wondering, is it intentional that harvesting hangs when invalid UTF-8 is encountered? I'm getting the following error and the harvesting stops.

`XML syntax error on line 567: invalid UTF-8` 

If it is possible, it would be nice if harvesting could continue even in the case of UTF-8 errors as it is in the case of HTTP errors if user has provided -ignore-http-errors flag. I'm using metha 0.1.15 installed via go get.

**Comment by miku** [comment] 2016-11-24 12:30
Thank for the bug report! 

> is it intentional that harvesting hangs when invalid UTF-8 is encountered

No, not intentional.

> If it is possible, it would be nice if harvesting could continue even in the case of UTF-8 errors

Yes, this might be a good idea. Do you have an example endpoint URL, where this problem occurs?

**Comment by mjlassila** [comment] 2016-11-27 18:32
Unfortunately the endpoint I'm using is in access restricted network but I'm glad that you found a suitable open endpoint for testing.

**Comment by miku** [comment] 2017-08-23 06:13
I cannot reproduce this error on my previous example [http://firstmonday.org/ojs/index.php/fm/oai](http://firstmonday.org/ojs/index.php/fm/oai). In case of not well formed XML, it might be OK to reject it. If you do not object, I would close this issue for now.

**Comment by mjlassila** [comment] 2017-08-24 05:23
Suits me, I'll create a new issue if I stumble upon this error again.We
resolved it by cleaning the source data which had some erroneous
characters.

**Comment by miku** [comment] 2017-08-24 08:15
Thanks!

**Closed by miku** 2017-08-24 08:15 UTC
